"""Initial IAM schema

Revision ID: 3161ef61df11
Revises: 
Create Date: 2026-05-20 15:56:57.894923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3161ef61df11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jit_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False), schema='iam')
    op.add_column('jit_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False), schema='iam')
    op.create_index(op.f('ix_iam_jit_sessions_id'), 'jit_sessions', ['id'], unique=False, schema='iam')
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False), schema='iam')
    op.create_index(op.f('ix_iam_roles_id'), 'roles', ['id'], unique=False, schema='iam')
    op.create_index(op.f('ix_iam_users_id'), 'users', ['id'], unique=False, schema='iam')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iam_users_id'), table_name='users', schema='iam')
    op.drop_index(op.f('ix_iam_roles_id'), table_name='roles', schema='iam')
    op.drop_column('roles', 'updated_at', schema='iam')
    op.drop_index(op.f('ix_iam_jit_sessions_id'), table_name='jit_sessions', schema='iam')
    op.drop_column('jit_sessions', 'updated_at', schema='iam')
    op.drop_column('jit_sessions', 'created_at', schema='iam')
    # ### end Alembic commands ###
